#ifndef Enum_h__
#define Enum_h__

enum RESOURCETYPE {RESOURCE_LOGO, RESOURCE_STAGE, RESOURCE_STATIC, RESOURCE_END};

enum MAIN_PLAYERSTATE
{
	MAIN_PLAYER_IDLE
	, MAIN_PLAYER_ATTACK
	, MAIN_PLAYER_MOVE
	, MAIN_PLAYER_SKILL
	, MAIN_PLAYER_DAMAGE
	, MAIN_PLAYER_END
	, MAIN_PLAYER_IDLE_MB
	, MAIN_PLAYER_ATTACK_MB
	, MAIN_PLAYER_MOVE_MB
	, MAIN_PLAYER_SKILL_MB
	, MAIN_PLAYER_DAMAGE_MB
	, MAIN_PLAYER_MB_END
};

enum PLAYERSTATE 
{ 
	PLAYER_IDLE
	, PLAYER_IDLE_MB
	, PLAYER_RUN
	, PLAYER_RUN_STOP
	, PLAYER_TELEPORT_MANA_STONE
	, PLAYER_DAMAGE_LIGHT_FRONT
	, PLAYER_DAMAGE_LIGHT_RIGHT
	, PLAYER_DAMAGE_LIGHT_BACK
	, PLAYER_DAMAGE_LIGHT_LEFT
	, PLAYER_DAMAGE_MIDDLE_FRONT_BEGIN
	, PLAYER_DAMAGE_MIDDLE_FRONT_END
	, PLAYER_DAMAGE_MIDDLE_BACK_BEGIN
	, PLAYER_DAMAGE_MIDDLE_BACK_END
	, PLAYER_TAKE_SNATCH
	, PLAYER_ATTACK_1
	, PLAYER_ATTACK_2
	, PLAYER_ATTACK_3
	, PLAYER_ATTACK_STRONG_1
	, PLAYER_ATTACK_STRONG_4
	, PLAYER_ATTACK_STRONG_5
	, PLAYER_MANA_BLADE
	, PLAYER_ATTACK_MB_STRONG_1
	, PLAYER_ATTACK_MB_STRONG_2
	, PLAYER_ATTACK_MB_STRONG_3
	, PLAYER_ATTACK_MB_STRONG_4
	, PLAYER_ATTACK_MB_STRONG_5
	, PLAYER_ATTACK_MB_STRONG_6
	, PLAYER_ATTACK_DOOMSAYER
	, PLAYER_ATTACK_RESONANCE
	, PLAYER_ATTACK_RUIN_BLACE
	, PLAYER_ATTACK_CASTLET_DIMENSION_HOLE
	, PLAYER_ATTACK_LORD_OF_MANA
	, PLAYER_DARK_KNIGHT_TANSFORMATION_BEGIN_1
	, PLAYER_DARK_KNIGHT_TANSFORMATION_BEGIN_2
	, PLAYER_DARK_KNIGHT_TANSFORMATION_END_1
	, PLAYER_SPEEDY_MOVE
	, PLAYER_MANA_REGION
};

enum MAIN_MONSTERSTATE
{
	MAIN_MONSTER_IDLE
	, MAIN_MONSTER_DASH
	, MAIN_MONSTER_TEIRD
	, MAIN_MONSTER_END
};

enum MONSTERSTATE
{
	MONSTER_IDLE
	, MONSTER_ATTACK_NORMAL
	, MONSTER_ATTACK_LOOK
	, MONSTER_ATTACK_2COMBO
	, MONSTER_ATTACK_3COMBO
	, MONSTER_ATTACK_4COMBO
	, MONSTER_DASH_BEGIN
	, MONSTER_DASH_BEGIN_SHORT
	, MONSTER_DASH_DURING
	, MONSTER_DASH_END_SHORT
	, MONSTER_DASH_END
	, MONSTER_ATTACK_MAGIC_SQUARE
	, MONSTER_ATTACK_MAGIC_SQUARE_DURING1
	, MONSTER_ATTACK_MAGIC_SQUARE_DURING2
	, MONSTER_ATTACK_MAGIC_SQUARE_END
	, MONSTER_ATTACK_JUMP_SMASH1
	, MONSTER_ATTACK_JUMP_SMASH2
	, MONSTER_ATTACK_FINAL_BEGIN
	, MONSTER_ATTACK_FINAL_DURING
	, MONSTER_ATTACK_FINAL_DURING_THROW
	, MONSTER_ATTACK_FINAL_END
	, MONSTER_END
};

enum eUI
{
	PLAYER_HP
	, PLAYER_HPMAX
	, MONSTER_HP
	, MONSTER_HPMAX
	, PLAYER_DAMAGE
	, MONSTER_DAMAGE
	, UI_END
};

enum CHANNEL_TYPE
{
	CHANNEL_BGM
	, CHANNEL_PLAYER_SOUND
	, CHANNEL_PLAYER_EFFECT
	, CHANNEL_PLAYER_EFFECT2
	, CHANNEL_MONSTER_SOUND
	, CHANNEL_MONSTER_EFFECT
	, CHANNEL_MONSTER_EFFECT2
	, CHANNEL_NONE_EFFECT
	, CHANNEL_END
};
#endif // Enum_h__

